"""add_branding_and_avatars

Revision ID: 20309e2890d1
Revises: 59b9b4c07e8f
Create Date: 2025-12-09 12:55:53.596442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20309e2890d1'
down_revision: Union[str, None] = '59b9b4c07e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('organizations', sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    op.add_column('organizations', sa.Column('secondary_color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('organizations', 'secondary_color')
    op.drop_column('organizations', 'primary_color')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
