"""add_online_meeting_url_to_room

Revision ID: 22a45ee15fd2
Revises: b843c0135d13
Create Date: 2025-12-19 23:39:04.429509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a45ee15fd2'
down_revision: Union[str, None] = 'b843c0135d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('online_meeting_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'online_meeting_url')
    # ### end Alembic commands ###
