"""add_event_comments_table

Revision ID: 5e1449c134e1
Revises: 2f4c11c73b62
Create Date: 2025-12-14 23:26:00.795096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e1449c134e1'
down_revision: Union[str, None] = '2f4c11c73b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_comments_event_id'), 'event_comments', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_comments_id'), 'event_comments', ['id'], unique=False)
    op.create_index(op.f('ix_event_comments_is_deleted'), 'event_comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_event_comments_user_id'), 'event_comments', ['user_id'], unique=False)
    # Note: SQLite doesn't support ALTER COLUMN TYPE, so we skip the departments.description change
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_comments_user_id'), table_name='event_comments')
    op.drop_index(op.f('ix_event_comments_is_deleted'), table_name='event_comments')
    op.drop_index(op.f('ix_event_comments_id'), table_name='event_comments')
    op.drop_index(op.f('ix_event_comments_event_id'), table_name='event_comments')
    op.drop_table('event_comments')
    # ### end Alembic commands ###
