"""add_user_availability_schedules

Revision ID: 76409f8b87ac
Revises: 86289b23d98e
Create Date: 2025-12-17 12:34:58.759287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76409f8b87ac'
down_revision: Union[str, None] = '86289b23d98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_availability_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_availability_schedules_id'), 'user_availability_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_user_availability_schedules_user_id'), 'user_availability_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_availability_schedules_user_id'), table_name='user_availability_schedules')
    op.drop_index(op.f('ix_user_availability_schedules_id'), table_name='user_availability_schedules')
    op.drop_table('user_availability_schedules')
    # ### end Alembic commands ###
