"""add_user_departments_and_organizations_many_to_many

Revision ID: 79f4916dd82c
Revises: 20309e2890d1
Create Date: 2025-12-14 22:05:09.136871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79f4916dd82c'
down_revision: Union[str, None] = '20309e2890d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_departments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'department_id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_user_departments_department_id'), 'user_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_departments_user_id'), 'user_departments', ['user_id'], unique=False)
    op.create_table('user_organizations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_user_organizations_organization_id'), 'user_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_user_id'), 'user_organizations', ['user_id'], unique=False)
    op.alter_column('departments', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=True)
    op.drop_index('ix_departments_name', table_name='departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.alter_column('departments', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_organizations_user_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_organization_id'), table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_index(op.f('ix_user_departments_user_id'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_department_id'), table_name='user_departments')
    op.drop_table('user_departments')
    # ### end Alembic commands ###
