"""add_admin_notifications

Revision ID: 86289b23d98e
Revises: c1b2c3d4e5f6
Create Date: 2025-12-16 20:48:09.362050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '86289b23d98e'
down_revision: Union[str, None] = 'c1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('target_user_ids', sa.JSON(), nullable=True),
    sa.Column('target_department_ids', sa.JSON(), nullable=True),
    sa.Column('display_duration_hours', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_created_at'), 'admin_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_created_by'), 'admin_notifications', ['created_by'], unique=False)
    op.create_index(op.f('ix_admin_notifications_expires_at'), 'admin_notifications', ['expires_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_is_active'), 'admin_notifications', ['is_active'], unique=False)
    op.create_table('admin_notification_dismissals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['admin_notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notification_dismissals_dismissed_at'), 'admin_notification_dismissals', ['dismissed_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_dismissals_id'), 'admin_notification_dismissals', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notification_dismissals_notification_id'), 'admin_notification_dismissals', ['notification_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_dismissals_user_id'), 'admin_notification_dismissals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_notification_dismissals_user_id'), table_name='admin_notification_dismissals')
    op.drop_index(op.f('ix_admin_notification_dismissals_notification_id'), table_name='admin_notification_dismissals')
    op.drop_index(op.f('ix_admin_notification_dismissals_id'), table_name='admin_notification_dismissals')
    op.drop_index(op.f('ix_admin_notification_dismissals_dismissed_at'), table_name='admin_notification_dismissals')
    op.drop_table('admin_notification_dismissals')
    op.drop_index(op.f('ix_admin_notifications_is_active'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_expires_at'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_by'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_at'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
