"""add_soft_delete_to_notifications

Revision ID: a1b2c3d4e5f6
Revises: 7bc52a075064
Create Date: 2025-11-30 23:42:37.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '7bc52a075064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('notifications', 'is_deleted')
    # ### end Alembic commands ###

