"""add_department_color

Revision ID: ab13f75e1043
Revises: bb8a1ac540a8
Create Date: 2025-12-19 21:07:21.497848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab13f75e1043'
down_revision: Union[str, None] = 'bb8a1ac540a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('color', sa.String(length=7), nullable=True))
    # Note: Skipping ALTER COLUMN and index operations for SQLite compatibility
    # op.alter_column('departments', 'description', ...) - SQLite doesn't support ALTER COLUMN
    # op.drop_index('ix_departments_name', table_name='departments')
    # op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    # op.drop_index('ix_user_availability_schedules_user_id', table_name='user_availability_schedules')
    # op.create_index(op.f('ix_user_availability_schedules_user_id'), 'user_availability_schedules', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_availability_schedules_user_id'), table_name='user_availability_schedules')
    op.create_index('ix_user_availability_schedules_user_id', 'user_availability_schedules', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.alter_column('departments', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_column('departments', 'color')
    # ### end Alembic commands ###
