"""add_access_availability_slots_to_user

Revision ID: b843c0135d13
Revises: ab13f75e1043
Create Date: 2025-12-19 22:48:19.297680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b843c0135d13'
down_revision: Union[str, None] = 'ab13f75e1043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_availability_slots', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_availability_slots')
    # ### end Alembic commands ###
