"""add_availability_slots_table

Revision ID: bb8a1ac540a8
Revises: 76409f8b87ac
Create Date: 2025-12-19 20:00:08.449655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8a1ac540a8'
down_revision: Union[str, None] = '76409f8b87ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('process_name', sa.String(length=255), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('booked_by', sa.Uuid(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_booked_by'), 'availability_slots', ['booked_by'], unique=False)
    op.create_index(op.f('ix_availability_slots_ends_at'), 'availability_slots', ['ends_at'], unique=False)
    op.create_index(op.f('ix_availability_slots_event_id'), 'availability_slots', ['event_id'], unique=False)
    op.create_index(op.f('ix_availability_slots_id'), 'availability_slots', ['id'], unique=False)
    op.create_index(op.f('ix_availability_slots_process_name'), 'availability_slots', ['process_name'], unique=False)
    op.create_index(op.f('ix_availability_slots_starts_at'), 'availability_slots', ['starts_at'], unique=False)
    op.create_index(op.f('ix_availability_slots_status'), 'availability_slots', ['status'], unique=False)
    op.create_index(op.f('ix_availability_slots_user_id'), 'availability_slots', ['user_id'], unique=False)
    op.drop_index('ix_ticketattachment_id', table_name='ticketattachment')
    op.drop_index('ix_ticketattachment_is_deleted', table_name='ticketattachment')
    op.drop_index('ix_ticketattachment_ticket_id', table_name='ticketattachment')
    op.drop_index('ix_ticketattachment_uploaded_by', table_name='ticketattachment')
    op.drop_table('ticketattachment')
    op.drop_index('ix_ticketcomment_id', table_name='ticketcomment')
    op.drop_index('ix_ticketcomment_is_deleted', table_name='ticketcomment')
    op.drop_index('ix_ticketcomment_ticket_id', table_name='ticketcomment')
    op.drop_index('ix_ticketcomment_user_id', table_name='ticketcomment')
    op.drop_table('ticketcomment')
    op.alter_column('departments', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_departments_name', table_name='departments')
    op.create_index(op.f('ix_tickets_title'), 'tickets', ['title'], unique=False)
    op.drop_index('ix_user_availability_schedules_user_id', table_name='user_availability_schedules')
    op.create_index(op.f('ix_user_availability_schedules_user_id'), 'user_availability_schedules', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_availability_schedules_user_id'), table_name='user_availability_schedules')
    op.create_index('ix_user_availability_schedules_user_id', 'user_availability_schedules', ['user_id'], unique=False)
    op.drop_index(op.f('ix_tickets_title'), table_name='tickets')
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.alter_column('departments', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.create_table('ticketcomment',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('ticket_id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('content', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticketcomment_user_id', 'ticketcomment', ['user_id'], unique=False)
    op.create_index('ix_ticketcomment_ticket_id', 'ticketcomment', ['ticket_id'], unique=False)
    op.create_index('ix_ticketcomment_is_deleted', 'ticketcomment', ['is_deleted'], unique=False)
    op.create_index('ix_ticketcomment_id', 'ticketcomment', ['id'], unique=False)
    op.create_table('ticketattachment',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('ticket_id', sa.CHAR(length=32), nullable=False),
    sa.Column('uploaded_by', sa.CHAR(length=32), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticketattachment_uploaded_by', 'ticketattachment', ['uploaded_by'], unique=False)
    op.create_index('ix_ticketattachment_ticket_id', 'ticketattachment', ['ticket_id'], unique=False)
    op.create_index('ix_ticketattachment_is_deleted', 'ticketattachment', ['is_deleted'], unique=False)
    op.create_index('ix_ticketattachment_id', 'ticketattachment', ['id'], unique=False)
    op.drop_index(op.f('ix_availability_slots_user_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_status'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_starts_at'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_process_name'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_event_id'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_ends_at'), table_name='availability_slots')
    op.drop_index(op.f('ix_availability_slots_booked_by'), table_name='availability_slots')
    op.drop_table('availability_slots')
    # ### end Alembic commands ###
