"""add_event_participants

Revision ID: d56578feb442
Revises: 6c2d8c1a4f62
Create Date: 2025-11-25 20:55:07.886447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd56578feb442'
down_revision: Union[str, None] = '6c2d8c1a4f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participants',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('response_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id'),
    sqlite_autoincrement=False
    )
    # Note: ix_calendar_members_user_id may not exist, check first
    try:
        op.drop_index('ix_calendar_members_user_id', table_name='calendar_members')
    except:
        pass
    # Note: room_id foreign key may already exist, check first
    try:
        op.create_foreign_key(None, 'events', 'rooms', ['room_id'], ['id'])
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_index('ix_calendar_members_user_id', 'calendar_members', ['user_id'], unique=False)
    op.drop_table('event_participants')
    # ### end Alembic commands ###
