"""add_group_participants_and_override_rights

Revision ID: e1a2b3c4d5f6
Revises: 2f4c11c73b62
Create Date: 2026-01-16 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1a2b3c4d5f6'
down_revision: Union[str, None] = '2f4c11c73b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Добавляем право игнорировать проверку занятости
    op.add_column('users', sa.Column('can_override_availability', sa.Boolean(), nullable=False, server_default='false'))
    
    # Создаем таблицу групповых участников событий
    op.create_table('event_group_participants',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('event_id', sa.Uuid(), nullable=False),
        sa.Column('group_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('group_id', sa.Uuid(), nullable=False),
        sa.Column('added_by', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id', 'group_type', 'group_id', name='unique_event_group'),
        sqlite_autoincrement=False
    )
    op.create_index(op.f('ix_event_group_participants_event_id'), 'event_group_participants', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_group_participants_group_type'), 'event_group_participants', ['group_type'], unique=False)
    op.create_index(op.f('ix_event_group_participants_group_id'), 'event_group_participants', ['group_id'], unique=False)
    op.create_index(op.f('ix_event_group_participants_id'), 'event_group_participants', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_group_participants_id'), table_name='event_group_participants')
    op.drop_index(op.f('ix_event_group_participants_group_id'), table_name='event_group_participants')
    op.drop_index(op.f('ix_event_group_participants_group_type'), table_name='event_group_participants')
    op.drop_index(op.f('ix_event_group_participants_event_id'), table_name='event_group_participants')
    op.drop_table('event_group_participants')
    op.drop_column('users', 'can_override_availability')
    # ### end Alembic commands ###

