"""add_schedule_access_permissions_table

Revision ID: f02947049b63
Revises: ab13f75e1043
Create Date: 2025-12-29 21:35:14.067359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02947049b63'
down_revision: Union[str, None] = 'ab13f75e1043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_access_permissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("granted_to_user_id", sa.Uuid(), nullable=False),
        sa.Column("target_user_id", sa.Uuid(), nullable=True),
        sa.Column("target_department_id", sa.Uuid(), nullable=True),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["granted_to_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_schedule_access_permissions_id"),
        "schedule_access_permissions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_access_permissions_granted_to_user_id"),
        "schedule_access_permissions",
        ["granted_to_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_access_permissions_target_user_id"),
        "schedule_access_permissions",
        ["target_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_access_permissions_target_department_id"),
        "schedule_access_permissions",
        ["target_department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_access_permissions_granted_by_user_id"),
        "schedule_access_permissions",
        ["granted_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_schedule_access_permissions_granted_by_user_id"),
        table_name="schedule_access_permissions",
    )
    op.drop_index(
        op.f("ix_schedule_access_permissions_target_department_id"),
        table_name="schedule_access_permissions",
    )
    op.drop_index(
        op.f("ix_schedule_access_permissions_target_user_id"),
        table_name="schedule_access_permissions",
    )
    op.drop_index(
        op.f("ix_schedule_access_permissions_granted_to_user_id"),
        table_name="schedule_access_permissions",
    )
    op.drop_index(
        op.f("ix_schedule_access_permissions_id"),
        table_name="schedule_access_permissions",
    )
    op.drop_table("schedule_access_permissions")
    # ### end Alembic commands ###
